### PR TITLE
fix debug skip in puppet

### PR DESCRIPTION
**Pull request by binary1230**
- this is a little uglier than I would like, but, it gives the ability to skip parts of the puppet deploy when you just want to test INI settings
- this setting is a thing we lost in the puppet refactor that I never got around to putting back in
- reduces deploy time for INI testing from 7 minutes to 40 seconds

### CODE REVIEW

**Comment by binary1230** [comment]
diff looks a little complex, but mostly is wrapping stuff in an if statement

**Comment by binary1230** [comment]
must merge https://github.com/magfest/ubersystem-puppet/pull/85 at same time

**Comment by kitsuta** [comment]
I expect you mean this must be merged with #49, since this IS #85. :P

+1 will be super happy when puppet redeploys are fast

**Comment by binary1230** [comment]
THIS ONE: https://github.com/magfest/ubersystem-deploy/pull/49 : )

**Comment by EliAndrewC** [comment]
+1 (belated OMHBITY)

**Pull request merged**
