### PR TITLE
Added "food_restriction" and "sandwich" sections

### PR DESCRIPTION
**Pull request by EliAndrewC**
These sections are now puppetized.

### CODE REVIEW

**Comment by EliAndrewC** [comment]
Ack!  I didn't mean to click the merge button!

**Comment by earl7399** [comment]
+1

**Comment by kitsuta** [comment]
Doing work in the middle of the night on a thing we want to launch that night, while no one else is around, is probably a good case for merging stuff on your own. :stuck_out_tongue:

**Comment by binary1230** [comment]
+1

**Pull request merged**
