### PR TITLE
puppetized volunteer checklist

### PR DESCRIPTION
**Pull request by EliAndrewC**
I could have sworn I made a PR for this last night when I pushed the branch.  But apparently I didn't and instead only pushed the branch without actually making a PR.  Derp.

### CODE REVIEW

**Comment by EliAndrewC** [comment]
https://github.com/magfest/production-config/pull/38 relies on this, and I need this to do my deploy tonight, so since this is a MAGFest-specific repo I'm gonna go ahead and merge it now.  I'll do the usual test on staging before I deploy to production.

**Comment by binary1230** [comment]
solid +1

only question is:

if there isn't anything in the checklist, is it ok to have just this text in the INI (seems like it would be):

```
[volunteer_checklist]
# followed by another [section] with nothing in between
```

**Comment by EliAndrewC** [comment]
Yes, it's fine in ``ConfigObj`` (and in the ``ini`` file format generally) to have two empty sections next to each other such as

```
[foo]
[bar]
```

Our config won't get confused and thing ``[bar]`` is a subsection or anything because if it were then we'd say

```
[foo]
[[bar]]
```

and it also won't complain about empty sections in general.

**Comment by binary1230** [comment]
cool, then +2

**Pull request merged**
