### PR TITLE
Merge AC-WIP with master, more variables

### PR DESCRIPTION
**Pull request by ksonney**
This syncs up the anthroconWIP with master, and adds a couple of additional variables not covered yet.

### CODE REVIEW

**Comment by binary1230** [comment]
I'll get back to this one after magstock

**Comment by binary1230** [comment]
this one's pretty far diverged from everything now so was thinking about closing it unless anyone has objections.  I ended up integrating a lot of this already, when you guys are ready to launch AC for next year, I can help integrate any other ones needed so we have a unified module here. or, if we get the docker stuff done, then none of this matters anymore.

**Comment by kitsuta** [comment]
Yeah, @ksonney can we close this?

**Comment by ksonney** [comment]
Yeah, this one can die. We'll figure something out for RAMS as we progress on the buildout there.

**Pull request closed without merging**
