### PR TITLE
Add deadlines to bands plugin config

### PR DESCRIPTION
**Pull request by kitsuta**
Since the deadlines are likely to change, events can now set them.

### CODE REVIEW

**Comment by kitsuta** [comment]
Gah, merge conflicts. That is what I get for not updating this repo first.

I'll resolve them once I get a +1.

**Comment by kitsuta** [comment]
OK, this doesn't actually work because Ruby is somehow evaluating an empty string to falsey even though I read that it is more strict than that. Closing this and creating a new PR.

**Comment by binary1230** [comment]
hm, this should work where if we don't set the value in puppet, the INI sections don't get written out and it defaults to whatever's in configspec.ini (which are the wrong dates but they are valid dates).

**Comment by binary1230** [comment]
it seems like that's what we'd want if that's the case?

**Comment by kitsuta** [comment]
No, we explicitly want to be able to set these dates to an empty string since that is how you turn off steps. When I tried that, though, puppet didn't actually apply them.

**Pull request closed without merging**
