### PR TITLE
log to stderr when using vagrant

### PR DESCRIPTION
**Pull request by binary1230**
- makes it easier to debug in IDEs and command line

also merge with:
https://github.com/magfest/ubersystem-deploy/pull/38

### CODE REVIEW

**Comment by EliAndrewC** [comment]
Suppose I say ``sudo supervisorctl restart all`` in a terminal where I've SSHed into my Vagrant box.  If this is turned on, does that mean that all of the logging will be spit out to that terminal?  If so, that pretty much makes that terminal unusable, even though the process is backgrounded.

Generally when I want to look at logs, I just do ``sudo tail -F /var/log/syslog`` and then let that run.  Then I can Ctrl+c out of it when I'm done.  This seems like that, but without the option of making the log messages stop, right?

I'm not super opposed to this, since I can always turn it off on my own local dev box, but unless I've misunderstood something it seems unnecessary and terminal-eating.

**Comment by binary1230** [comment]
supervisor should catch all the log output and log it, it just means we'll be duplicating logs twice, but on dev boxes, doesn't really matter.  it won't spew to your screen, and local dev boxes aren't gonna run out of space.

the only reason we aren't logging to stdout currently is we started filling up the log files last year in production with email sending gone off the rails spewing tons of output, and syslog will compress them automatically.

the main reason I wanted it was to print stdout inside an attached debugger, like pycharm.

**Comment by binary1230** [comment]
on local boxes this will just cause more output to /var/log/supervisor/ubersystem_vagrant_daemon

**Comment by EliAndrewC** [comment]
Gotcha, makes sense.  +1 in that case, feel free to merge this whenever it makes sense to do so.

**Comment by binary1230** [comment]
actually ok also, technically, this change just allows the option, the other PR turns it on from vagrant

**Pull request merged**
