### PR TITLE
Big puppet refactor - uber puppet module

### PR DESCRIPTION
**Pull request by binary1230**
# DO NOT MERGE!!

This code is now ready to go, but, needs to be merged extremely carefully. Only Dom should merge it.
# summary
- massive refactoring of the entire ubersystem puppet module
- break out all pieces into their individual components and make the entire thing modular
- this means that if someone wants to run the backend app, or not run nginx, or not mess with firewall rules, they don't have to include those parts.  or they could just run the DB only and just do replication.
- default is to include all of the components, which is what most people are going to want
- HUGE overhaul of all dependency management, things actually only fire off when they're needed, which is how it was supposed to be.  for example, we only run pip to install dependencies when there was new code pulled down by the git module.  this should help speed things up a lot when doing deploys both locally and on production nodes.
- moved all config stuff to its own class so it's obvious what is -just- config
- create a default index.html page if you browse to /, it no longer 404's.
- still need to remove some mag-specific default values from the puppet module, but now that's pretty easy to do

requires:
- https://github.com/magfest/ubersystem-deploy/pull/36
- https://github.com/magfest/production-config/pull/26

### CODE REVIEW

**Comment by kitsuta** [comment]
Looks good, though this is a bit over my head.

**Comment by EliAndrewC** [comment]
> Looks good, though this is a bit over my head.

The PR nomenclature for this is "OMHBITY" (Over My Head But I Trust You).  My preferred pronunciation is "om-bitty".  :P

**Comment by binary1230** [comment]
FYI, this is now ready to go.  @kitsuta and I will be merging this within the hour

**Comment by binary1230** [comment]
re-reviewed, internal +1

**Comment by binary1230** [comment]
one interesting tidbit I forgot to mention:

puppet now has the concept of 2 different lists of sideboard plugins to install:
* 'regular' plugins.  the idea being that these will be defined by the common.yaml file that everyone uses.  in the future when we keep breaking up ubersystem into a bunch of different plugins, they'll go in here.
* 'extra' plugins.  these are for event-specific plugins like magstock, magprime, magclassic, etc.

So, events can override one or the other without having to worry to remember which core plugins are supposed to go in/etc.

**Comment by binary1230** [comment]
fixes https://github.com/magfest/ubersystem/issues/1336

**Comment by binary1230** [comment]
fixes https://github.com/magfest/ubersystem/issues/1335

**Pull request merged**
