### PR TITLE
Fixes #135: Adds 10s cache to NGINX config for preregistration form

### LINKED ISSUE #135: Cache preregistration page for ~15s (/uber/preregistration/form)
Per our [load tests](https://docs.magfest.net/display/EN/Uber+Preregistration+Load+Test+Results+2017-05-16), in order to handle the preregistration traffic spike, we should cache our preregistration form.

The preregistration form can't be cached in perpetuity because it will change as more people register (badge prices will increase). But even caching it for a short window - like 15 seconds - will make a huge difference when we get a wave of people registering.

### PR DESCRIPTION
**Pull request by RobRuana**
This pull request requires https://github.com/magfest/ubersystem/pull/2575 for preregistration on our deployments to work correctly.

Fixes #135

### CODE REVIEW

**Comment by jcooter** [comment]
Why include the $request_body as your proxy_cache_key?  That seems overly selective.

**Comment by RobRuana** [comment]
$request_body was literally copy/pasted from our other caching config. There's no reason for it in this context. It shouldn't hurt one way or another, but I'll take it out.

**Comment by jcooter** [comment]
Having the request_body cached will generate a new cached page on disk for every request body that is in any way different - since there are numerous things that would cause a request body to be different (browser/OS combo, browser plugins, privacy settings, etc) it would lead to a lot of unnecessary and useless cache objects being created on disk.

**Comment by jcooter** [comment]
Apart from that, LGTM

**Pull request merged**
